FROM wordpress:php8.2-apache

# install system dependency 
RUN apt-get update && apt-get install -y \
    git unzip curl less nano zip libzip-dev libonig-dev libpng-dev libicu-dev libxml2-dev \
    nodejs npm

# Install Node.js v18.20 and npm
# RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
#     apt-get install -y nodejs && \
#     npm install -g npm@latest

# Install Composer 
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


# Install WP CLI 
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/local/bin/wp

# Optional: Install Yarn
RUN npm install -g yarn

WORKDIR /var/www/html